// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA68B83vERAiSxj-RE9HGwT4eDK3GhGWxw',
    appId: '1:459038662972:android:2fa51c3cb587314cf6fe39',
    messagingSenderId: '459038662972',
    projectId: 'gorget-store-last-one',
    databaseURL: 'https://gorget-store-last-one-default-rtdb.firebaseio.com',
    storageBucket: 'gorget-store-last-one.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5Fz702rG1rgW8lqAVdMFsYj613ESI6BU',
    appId: '1:459038662972:ios:770479cefdfab295f6fe39',
    messagingSenderId: '459038662972',
    projectId: 'gorget-store-last-one',
    databaseURL: 'https://gorget-store-last-one-default-rtdb.firebaseio.com',
    storageBucket: 'gorget-store-last-one.appspot.com',
    androidClientId: '459038662972-g600titoauo7nded3uq53vchgq611f5c.apps.googleusercontent.com',
    iosClientId: '459038662972-hpn8vjqcnrgpb9b40qh36udv7u2rr5dc.apps.googleusercontent.com',
    iosBundleId: 'harir.store.com',
  );
}
