// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkVVxXH_pa1CgQn3VCFivuQe37-PRN5II',
    appId: '1:459038662972:web:a5e3200d4331bb86f6fe39',
    messagingSenderId: '459038662972',
    projectId: 'gorget-store-last-one',
    authDomain: 'gorget-store-last-one.firebaseapp.com',
    storageBucket: 'gorget-store-last-one.appspot.com',
    measurementId: 'G-R61FQ6DVX5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA68B83vERAiSxj-RE9HGwT4eDK3GhGWxw',
    appId: '1:459038662972:android:670c9638fbd7e793f6fe39',
    messagingSenderId: '459038662972',
    projectId: 'gorget-store-last-one',
    storageBucket: 'gorget-store-last-one.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5Fz702rG1rgW8lqAVdMFsYj613ESI6BU',
    appId: '1:459038662972:ios:12f389620a348a9df6fe39',
    messagingSenderId: '459038662972',
    projectId: 'gorget-store-last-one',
    storageBucket: 'gorget-store-last-one.appspot.com',
    iosClientId: '459038662972-c96bd2s0f9s6nu2sovl3s0idsejlj8ao.apps.googleusercontent.com',
    iosBundleId: 'harir.store.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5Fz702rG1rgW8lqAVdMFsYj613ESI6BU',
    appId: '1:459038662972:ios:8babded9c9d67673f6fe39',
    messagingSenderId: '459038662972',
    projectId: 'gorget-store-last-one',
    storageBucket: 'gorget-store-last-one.appspot.com',
    iosClientId: '459038662972-mgn3sc7udu2sfuaiapr7m4fv8tt5npos.apps.googleusercontent.com',
    iosBundleId: 'harir.store.com.RunnerTests',
  );
}
